services:
  mariadb:
    container_name: mydb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile 
    # restart: always
    env_file: .env
    volumes:
      - database_data:/var/lib/mysql
    networks:
      - inception

  wordpress:
    container_name: mywp
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile 
    # restart: always
    env_file: .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb

  nginx:
    container_name: mynginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile 
    # restart: always
    env_file: .env
    ports:
      - 80:443
    volumes:
      - wordpress_data:/var/www/html:ro
    networks:
      - inception
    depends_on:
      - wordpress

volumes:
  wordpress_data:
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wordpress_data
  database_data:
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/database_data

networks:
  inception:
    name: inception
    driver: bridge
