services:
  mariadb:
    container_name: mydb
    image: mariadb:10.2.10
    # build: ./requirements/mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${VOLUMES_PATH}/database:/var/lib/mysql
      - ./srcs/requirements/mariadb/conf:/etc/mysql/conf.d:ro
      # - /etc/mysql/conf.d
    networks:
      - ${MY_NETWORK}

  wordpress:
    container_name: mywp
    image: wordpress:4.8.3-php7.1-fpm-alpine
    # build: ./requirements/wordpress
    environment:
      - WORDPRESS_DB_HOST=mydb
      - WORDPRESS_DB_USER=${WP_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WP_DB_PASSWORD}
      - WORDPRESS_DB_NAME=${WP_DB_NAME}
      - WORDPRESS_TABLE_PREFIX=wp_
    volumes:
      - ${VOLUMES_PATH}/website:/var/www/html
    networks:
      - ${MY_NETWORK}
    depends_on:
      - mariadb

  nginx:
    container_name: mynginx
    # image: nginx:1.12.2-alpine
    build: ./requirements/nginx
    ports:
      - 80:80
      - 443:443
      - 4242:4242
    volumes:
      - ${VOLUMES_PATH}/website:/var/www/html:ro
    networks:
      - ${MY_NETWORK}
    depends_on:
      - wordpress

networks:
  mynet:
    name: ${MY_NETWORK}
  
# volumes:
#   wordpress-db:
#   wordpress-website: