services:
  mariadb:
    container_name: mariadb
    image: mariadb
    pull_policy: never
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile 
    restart: always
    env_file: .env
    volumes:
      - database_data:/var/lib/mysql
    networks:
      - inception

  wordpress:
    container_name: wordpress
    image: wordpress
    pull_policy: never
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile 
    restart: always
    env_file: .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb

  nginx:
    container_name: nginx
    image: nginx
    pull_policy: never
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile 
    restart: always
    env_file: .env
    ports:
      - 443:443
    volumes:
      - wordpress_data:/var/www/html:ro
    networks:
      - inception
    depends_on:
      - wordpress
      - mariadb

volumes:
  wordpress_data:
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wordpress_data
  database_data:
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/database_data

networks:
  inception:
    name: inception
    driver: bridge
